# Generated by Django 3.2.4 on 2021-06-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_titlechange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Titlechange',
        ),
    ]
